name       : perl-extutils-config
version    : 0.008
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz : ae5104f634650dce8a79b7ed13fb59d67a39c213a6776cfdaa3ee749e62f1a8c
license    : Artistic-2.0
component  : programming.perl
summary    : A wrapper for perl's configuration
description: |
    A wrapper for perl's configuration
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
